# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\物联网应用\python\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(608, 506)
        # palette = QtGui.QPalette()
        # # palette.setBrush(, QtGui.QBrush(QtGui.QPixmap("cat.jpg"))
        # palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(QtGui.QPixmap("cat.jpg")))
        
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(190, 450, 191, 32))
        self.buttonBox.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.Temp = QtWidgets.QLCDNumber(Dialog)
        self.Temp.setGeometry(QtCore.QRect(40, 50, 231, 121))
        self.Temp.setObjectName("Temp")
        self.Temp.display(21.5)   #显示温度
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 10, 131, 41))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.Humi = QtWidgets.QLCDNumber(Dialog)
        self.Humi.setGeometry(QtCore.QRect(330, 50, 231, 121))
        self.Humi.setObjectName("Humi")
        self.Humi.display(40)   #显示湿度
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(380, 10, 131, 41))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(40, 180, 521, 251))
        self.graphicsView.setObjectName("graphicsView")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # 确定按钮
        self.buttonBox.rejected.connect(Dialog.reject) # 取消按钮
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap('test.ico'), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setWindowTitle(_translate("Dialog", "房彬彬"))
        self.label.setText(_translate("Dialog", "Temp"))
        self.label_2.setText(_translate("Dialog", "Humi"))

if __name__=='__main__':
    import sys
    app=QtWidgets.QApplication(sys.argv)
    palette = QtGui.QPalette()
    palette.setBrush(QtGui.QPalette.Background, QtGui.QBrush(QtGui.QPixmap("cat.jpg")))
    app.setPalette(palette)
    Dialog=QtWidgets.QDialog()
    ui=Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
