# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\物联网应用\python\End_of_Period\test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1286, 735)
        self.Temp = QtWidgets.QLCDNumber(Dialog)
        self.Temp.setGeometry(QtCore.QRect(60, 50, 281, 121))
        self.Temp.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Temp.setObjectName("Temp")
        self.temp_label = QtWidgets.QLabel(Dialog)
        self.temp_label.setGeometry(QtCore.QRect(120, 10, 131, 41))
        self.temp_label.setMinimumSize(QtCore.QSize(16, 17))
        self.temp_label.setSizeIncrement(QtCore.QSize(12, 15))
        self.temp_label.setBaseSize(QtCore.QSize(16, 11))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.temp_label.setFont(font)
        self.temp_label.setAlignment(QtCore.Qt.AlignCenter)
        self.temp_label.setWordWrap(False)
        self.temp_label.setObjectName("temp_label")
        self.graphicsView = QChartView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(30, 190, 741, 511))
        self.graphicsView.setObjectName("graphicsView")
        self.humi_label = QtWidgets.QLabel(Dialog)
        self.humi_label.setGeometry(QtCore.QRect(520, 10, 131, 41))
        self.humi_label.setMinimumSize(QtCore.QSize(16, 17))
        self.humi_label.setSizeIncrement(QtCore.QSize(12, 15))
        self.humi_label.setBaseSize(QtCore.QSize(16, 11))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.humi_label.setFont(font)
        self.humi_label.setAlignment(QtCore.Qt.AlignCenter)
        self.humi_label.setWordWrap(False)
        self.humi_label.setObjectName("humi_label")
        self.Humi = QtWidgets.QLCDNumber(Dialog)
        self.Humi.setGeometry(QtCore.QRect(460, 50, 281, 121))
        self.Humi.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Humi.setObjectName("Humi")
        self.history_label = QtWidgets.QLabel(Dialog)
        self.history_label.setGeometry(QtCore.QRect(800, 10, 131, 41))
        self.history_label.setMinimumSize(QtCore.QSize(16, 17))
        self.history_label.setSizeIncrement(QtCore.QSize(12, 15))
        self.history_label.setBaseSize(QtCore.QSize(16, 11))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.history_label.setFont(font)
        self.history_label.setAlignment(QtCore.Qt.AlignCenter)
        self.history_label.setWordWrap(False)
        self.history_label.setObjectName("history_label")
        self.end_time = QtWidgets.QDateTimeEdit(Dialog)
        self.end_time.setGeometry(QtCore.QRect(850, 131, 194, 31))
        self.end_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 7, 1), QtCore.QTime(0, 0, 0)))
        self.end_time.setObjectName("end_time")
        self.begain_time = QtWidgets.QDateTimeEdit(Dialog)
        self.begain_time.setGeometry(QtCore.QRect(850, 71, 194, 31))
        self.begain_time.setDateTime(QtCore.QDateTime(QtCore.QDate(2022, 3, 15), QtCore.QTime(0, 0, 0)))
        self.begain_time.setObjectName("begain_time")
        self.label_begain_time = QtWidgets.QLabel(Dialog)
        self.label_begain_time.setGeometry(QtCore.QRect(780, 80, 72, 15))
        self.label_begain_time.setObjectName("label_begain_time")
        self.label_end_time = QtWidgets.QLabel(Dialog)
        self.label_end_time.setGeometry(QtCore.QRect(780, 140, 72, 15))
        self.label_end_time.setObjectName("label_end_time")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(1090, 80, 93, 71))
        self.pushButton.setObjectName("pushButton")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(780, 190, 471, 511))
        self.tableView.setObjectName("tableView")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.temp_label.setText(_translate("Dialog", "Temp"))
        self.humi_label.setText(_translate("Dialog", "Humi"))
        self.history_label.setText(_translate("Dialog", "历史查询"))
        self.label_begain_time.setText(_translate("Dialog", "起始时间"))
        self.label_end_time.setText(_translate("Dialog", "结束时间"))
        self.pushButton.setText(_translate("Dialog", "查询"))
from PyQt5.QtChart import QChartView
