# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\物联网应用\python\tianzhuo\tianzhuo.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(835, 621)
        self.lcdNumber = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber.setGeometry(QtCore.QRect(40, 80, 161, 111))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_2.setGeometry(QtCore.QRect(240, 80, 161, 111))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(40, 250, 391, 311))
        self.tableView.setObjectName("tableView")
        self.graphicsView = QChartView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(490, 90, 311, 192))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_2 = QChartView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(490, 350, 311, 192))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(90, 50, 72, 15))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(280, 50, 72, 15))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(180, 210, 111, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(551, 50, 121, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(551, 320, 121, 20))
        self.label_5.setObjectName("label_5")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "当前温度："))
        self.label_2.setText(_translate("Dialog", "当前温度："))
        self.label_3.setText(_translate("Dialog", "历史数据"))
        self.label_4.setText(_translate("Dialog", "温度变化曲线"))
        self.label_5.setText(_translate("Dialog", "湿度变化曲线"))
from PyQt5.QtChart import QChartView
